import type { Translations } from './types';

interface AppTranslations {
  en: Translations;
  ar: Translations;
}

export const translations: AppTranslations = {
  en: {
    // General
    appName: 'AI Invoice Extractor',
    toggleLanguage: 'العربية',
    loading: 'Loading...',
    usd: 'USD',
    jod: 'JOD',
    close: 'Close',
    cancel: 'Cancel',
    delete: 'Delete',
    actions: 'Actions',
    exportToExcel: 'Export to Excel',
    columns: 'Columns',
    toggleColumns: 'Toggle Columns',
    show: 'Show',
    invoiceFile: 'Invoice File',


    // Auth
    login: 'Sign In',
    loginTitle: 'Log In',
    loginSubtitle: 'Welcome back, please log in to continue.',
    loggingIn: 'Logging in...',
    signup: 'Create an account',
    signupTitle: 'Create an Account',
    signupSubtitle: 'Join us! It only takes a minute.',
    signingUp: 'Signing up...',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    welcome: 'Welcome',
    loginPrompt: 'Don\'t have an account?',
    signupPrompt: 'Already have an account?',
    invalidCredentials: 'Invalid email or password.',
    userExists: 'Email already registered.',
    signupSuccess: 'Signup successful! Please log in.',
    signupError: 'An error occurred during sign up. Please try again.',
    passwordTooShort: 'Password should be at least 6 characters long.',

    // Dashboard
    dashboardTitle: 'Invoice Dashboard',
    noFileSelected: 'No file selected',
    fileSelected: 'File selected:',
    processInvoice: 'Process Invoice',
    processing: 'Analyzing Invoice...',
    analyzingLayout: 'Analyzing document layout...',
    extractingText: 'Extracting text and figures...',
    identifyingLineItems: 'Identifying line items...',
    verifyingTotals: 'Verifying totals and amounts...',
    almostDone: 'Almost there, finalizing results...',
    extractionError: 'An error occurred while extracting data. Please try another file.',
    noInvoices: 'No purchase invoices yet. Upload one to get started.',
    newlyExtractedInvoice: 'Newly Extracted Invoice',
    savedInvoices: 'Purchase Invoices',
    saveInvoice: 'Save Invoice',
    saving: 'Saving...',
    invoiceSaved: 'Invoice data saved successfully!',
    saveError: 'Failed to save the invoice. Please ensure the database is correctly configured and try again.',
    addNewInvoice: 'Add New Purchase Invoice',
    addManually: 'Add Manually',
    manualInvoiceEntry: 'Manual Invoice Entry',
    backToInvoices: 'Back to Invoices',
    uploadAndProcessInvoice: 'Upload & Process Invoice',
    invoiceDetails: 'Purchase Invoice Details',
    deleteInvoice: 'Delete Purchase Invoice',
    deleteConfirmTitle: 'Confirm Deletion',
    deleteConfirmMessage: 'Are you sure you want to delete this purchase invoice? This action cannot be undone.',
    invoiceDeleted: 'Purchase invoice deleted successfully.',
    grandTotal: 'Grand Total',
    totalInvoices: 'Total Invoices',
    uploadBoxTitle: 'Add a New Purchase Invoice',
    uploadBoxSubtitle: 'Upload a PDF or use your camera to scan an invoice.',
    chooseFile: 'Choose File',
    uploadPDF: 'Upload PDF',
    scanWithCamera: 'Scan with Camera',
    cancelUpload: 'Cancel Upload',
    searchPlaceholder: 'Search by number, vendor, customer, or item...',
    dateFrom: 'From Date',
    dateTo: 'To Date',
    clearFilters: 'Clear Filters',
    
    // Camera
    capture: 'Capture',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    noCameraAccess: 'Could not access camera. Please check permissions.',
    or: 'OR',
    uploadImageOrPDF: 'Upload PDF or Image',

    // Payment Status
    paidInvoices: 'Paid Invoices',
    unpaidInvoices: 'Unpaid Invoices',
    markAsPaid: 'Mark as Paid',
    invoiceStatusUpdated: 'Invoice status updated successfully.',
    paid: 'Paid',
    unpaid: 'Unpaid',
    paymentStatus: 'Payment Status',
    filterByStatus: 'Filter by Status',
    all: 'All',


    // Invoice Table Headers
    invoiceNumber: 'Invoice #',
    vendorName: 'Vendor',
    customerName: 'Customer',
    invoiceDate: 'Date',
    totalAmount: 'Total Amount',
    items: 'Items',
    description: 'Description',
    quantity: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    addItem: 'Add Item',
    removeItem: 'Remove',
    uploader: 'Uploader',
  },
  ar: {
    // General
    appName: 'مستخرج الفواتير الذكي',
    toggleLanguage: 'English',
    loading: 'جار التحميل...',
    usd: 'دولار',
    jod: 'د.أ',
    close: 'إغلاق',
    cancel: 'إلغاء',
    delete: 'حذف',
    actions: 'إجراءات',
    exportToExcel: 'تصدير إلى Excel',
    columns: 'الأعمدة',
    toggleColumns: 'إظهار/إخفاء الأعمدة',
    show: 'إظهار',
    invoiceFile: 'ملف الفاتورة',

    // Auth
    login: 'دخول',
    loginTitle: 'تسجيل الدخول',
    loginSubtitle: 'مرحباً بك، يرجى تسجيل الدخول للمتابعة',
    loggingIn: 'جارِ تسجيل الدخول...',
    signup: 'أنشئ حساباً',
    signupTitle: 'إنشاء حساب جديد',
    signupSubtitle: 'انضم إلينا! الأمر لا يستغرق سوى دقيقة.',
    signingUp: 'جارِ إنشاء الحساب...',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    passwordPlaceholder: 'أدخل كلمة المرور',
    welcome: 'مرحباً',
    loginPrompt: 'ليس لديك حساب؟',
    signupPrompt: 'هل لديك حساب بالفعل؟',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    userExists: 'البريد الإلكتروني مسجل بالفعل.',
    signupSuccess: 'تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.',
    signupError: 'حدث خطأ أثناء إنشاء الحساب. يرجى المحاولة مرة أخرى.',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',

    // Dashboard
    dashboardTitle: 'لوحة تحكم الفواتير',
    noFileSelected: 'لم يتم اختيار ملف',
    fileSelected: 'الملف المختار:',
    processInvoice: 'معالجة الفاتورة',
    processing: 'جاري تحليل الفاتورة...',
    analyzingLayout: 'جاري تحليل تخطيط المستند...',
    extractingText: 'استخراج النصوص والأرقام...',
    identifyingLineItems: 'التعرف على بنود الفاتورة...',
    verifyingTotals: 'التحقق من المجاميع والمبالغ...',
    almostDone: 'شارفنا على الانتهاء، يتم تجهيز النتائج...',
    extractionError: 'حدث خطأ أثناء استخراج البيانات. يرجى تجربة ملف آخر.',
    noInvoices: 'لا توجد فواتير مشتريات حتى الآن. قم برفع فاتورة للبدء.',
    newlyExtractedInvoice: 'فاتورة مستخرجة حديثاً',
    savedInvoices: 'فواتير المشتريات',
    saveInvoice: 'حفظ الفاتورة',
    saving: 'جارِ الحفظ...',
    invoiceSaved: 'تم حفظ بيانات الفاتورة بنجاح!',
    saveError: 'فشل حفظ الفاتورة. يرجى التأكد من أن قاعدة البيانات مهيأة بشكل صحيح والمحاولة مرة أخرى.',
    addNewInvoice: 'إضافة فاتورة مشتريات جديدة',
    addManually: 'إضافة يدوية',
    manualInvoiceEntry: 'إدخال فاتورة يدوية',
    backToInvoices: 'العودة للفواتير',
    uploadAndProcessInvoice: 'رفع ومعالجة فاتورة',
    invoiceDetails: 'تفاصيل فاتورة المشتريات',
    deleteInvoice: 'حذف فاتورة المشتريات',
    deleteConfirmTitle: 'تأكيد الحذف',
    deleteConfirmMessage: 'هل أنت متأكد من رغبتك في حذف فاتورة المشتريات هذه؟ لا يمكن التراجع عن هذا الإجراء.',
    invoiceDeleted: 'تم حذف فاتورة المشتريات بنجاح.',
    grandTotal: 'المجموع الكلي',
    totalInvoices: 'مجموع الفواتير',
    uploadBoxTitle: 'إضافة فاتورة مشتريات جديدة',
    uploadBoxSubtitle: 'قم برفع ملف PDF أو استخدم الكاميرا لمسح فاتورة ضوئياً.',
    chooseFile: 'اختر ملف',
    uploadPDF: 'رفع ملف PDF',
    scanWithCamera: 'مسح بالكاميرا',
    cancelUpload: 'إلغاء الرفع',
    searchPlaceholder: 'ابحث بالرقم، البائع، العميل، أو البند...',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    clearFilters: 'مسح الفلاتر',

    // Camera
    capture: 'التقاط',
    retake: 'إعادة الالتقاط',
    usePhoto: 'استخدام الصورة',
    noCameraAccess: 'لا يمكن الوصول إلى الكاميرا. يرجى التحقق من الأذونات.',
    or: 'أو',
    uploadImageOrPDF: 'رفع PDF أو صورة',

    // Payment Status
    paidInvoices: 'الفواتير المدفوعة',
    unpaidInvoices: 'الفواتير غير المدفوعة',
    markAsPaid: 'تحديد كمدفوع',
    invoiceStatusUpdated: 'تم تحديث حالة الفاتورة بنجاح.',
    paid: 'مدفوعة',
    unpaid: 'غير مدفوعة',
    paymentStatus: 'حالة الدفع',
    filterByStatus: 'تصفية حسب الحالة',
    all: 'الكل',


    // Invoice Table Headers
    invoiceNumber: 'رقم الفاتورة',
    vendorName: 'البائع',
    customerName: 'العميل',
    invoiceDate: 'التاريخ',
    totalAmount: 'المبلغ الإجمالي',
    items: 'البنود',
    description: 'الوصف',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    total: 'الإجمالي',
    addItem: 'إضافة بند',
    removeItem: 'حذف',
    uploader: 'المستخدم',
  }
};