
import type { Translations } from './types';

interface AppTranslations {
  en: Translations;
  ar: Translations;
}

export const translations: AppTranslations = {
  en: {
    // General
    appName: 'AI Invoice Extractor',
    toggleLanguage: 'العربية',
    loading: 'Loading...',
    usd: 'USD',
    jod: 'JOD',
    close: 'Close',
    cancel: 'Cancel',
    delete: 'Delete',
    actions: 'Actions',
    exportToExcel: 'Export to Excel',
    columns: 'Columns',
    toggleColumns: 'Toggle Columns',
    show: 'Show',
    invoiceFile: 'Invoice File',


    // Auth
    login: 'Sign In',
    loginTitle: 'Log In',
    loginSubtitle: 'Welcome back, please log in to continue.',
    loggingIn: 'Logging in...',
    signup: 'Create an account',
    signupTitle: 'Create an Account',
    signupSubtitle: 'Join us! It only takes a minute.',
    signingUp: 'Signing up...',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    welcome: 'Welcome',
    loginPrompt: 'Don\'t have an account?',
    signupPrompt: 'Already have an account?',
    invalidCredentials: 'Invalid email or password.',
    userExists: 'Email already registered.',
    signupSuccess: 'Signup successful! Please log in.',
    signupError: 'An error occurred during sign up. Please try again.',
    passwordTooShort: 'Password should be at least 6 characters long.',

    // Dashboard
    dashboardTitle: 'Invoice Dashboard',
    noFileSelected: 'No file selected',
    fileSelected: 'File selected:',
    processInvoice: 'Process Invoice',
    processing: 'Analyzing Invoice...',
    analyzingLayout: 'Analyzing document layout...',
    extractingText: 'Extracting text and figures...',
    identifyingLineItems: 'Identifying line items...',
    verifyingTotals: 'Verifying totals and amounts...',
    almostDone: 'Almost there, finalizing results...',
    extractionError: 'An error occurred while extracting data. Please try another file.',
    extractionErrors: '{count} file(s) could not be processed.',
    noInvoices: 'No purchase invoices yet. Upload one to get started.',
    newlyExtractedInvoices: 'Newly Extracted Invoices',
    savedInvoices: 'Purchase Invoices',
    saveInvoice: 'Save Invoice',
    saveAllInvoices: 'Save All',
    clearAll: 'Clear All',
    saving: 'Saving...',
    invoiceSaved: 'Invoice data saved successfully!',
    saveError: 'Failed to save invoice: ',
    saveAllError: 'Some invoices could not be saved. Please review and try again.',
    reason: 'Reason',
    addNewInvoice: 'Add New Purchase Invoice',
    addManually: 'Add Manually',
    manualInvoiceEntry: 'Manual Invoice Entry',
    backToInvoices: 'Back to Invoices',
    uploadAndProcessInvoice: 'Upload & Process Invoice',
    invoiceDetails: 'Purchase Invoice Details',
    deleteInvoice: 'Delete Purchase Invoice',
    deleteConfirmTitle: 'Confirm Deletion',
    deleteConfirmMessage: 'Are you sure you want to delete this purchase invoice? This action cannot be undone.',
    deleteSelected: 'Delete Selected',
    deleteSelectedConfirmMessage: 'Are you sure you want to delete the {count} selected invoices? This action cannot be undone.',
    countSelected: '{count} Selected',
    invoiceDeleted: 'Purchase invoice deleted successfully.',
    invoicesDeleted: 'Selected invoices deleted successfully.',
    grandTotal: 'Grand Total',
    totalInvoices: 'Total Invoices',
    uploadBoxTitle: 'Add a New Purchase Invoice',
    uploadBoxSubtitle: 'Supports PDF, Images (JPG/PNG), Excel, and Word.',
    chooseFile: 'Choose Files',
    uploadDocument: 'Upload Document',
    docSubtitle: 'PDF, Word, Excel',
    uploadImage: 'Upload Image',
    imgSubtitle: 'JPG, PNG',
    uploadPDF: 'Upload File',
    scanWithCamera: 'Scan with Camera',
    fromScanner: 'From Scanner',
    cancelUpload: 'Cancel Upload',
    searchPlaceholder: 'Search by number, vendor, customer...',
    filterItem: 'Filter by Item Name',
    dateFrom: 'From Date',
    dateTo: 'To Date',
    clearFilters: 'Clear Filters',
    minAmount: 'Min Amount',
    maxAmount: 'Max Amount',
    listView: 'List View',
    gridView: 'Grid View',
    processingCost: 'Processing Cost',
    totalUnpaidAmount: 'Unpaid Amount',
    topVendorStat: 'Top Vendor',
    topItemStat: 'Top Item',
    
    // Camera
    capture: 'Capture',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    noCameraAccess: 'Could not access camera. Please check permissions.',
    or: 'OR',
    uploadImageOrPDF: 'Upload PDF, Img, Excel, Word',

    // Payment Status
    paidInvoices: 'Paid Invoices',
    unpaidInvoices: 'Unpaid Invoices',
    markAsPaid: 'Mark as Paid',
    invoiceStatusUpdated: 'Invoice status updated successfully.',
    paid: 'Paid',
    unpaid: 'Unpaid',
    paymentStatus: 'Payment Status',
    filterByStatus: 'Filter by Status',
    all: 'All',


    // Invoice Table Headers
    invoiceNumber: 'Invoice #',
    vendorName: 'Vendor',
    customerName: 'Customer',
    invoiceDate: 'Date',
    totalAmount: 'Total Amount',
    items: 'Items',
    description: 'Description',
    quantity: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    addItem: 'Add Item',
    removeItem: 'Remove',
    uploader: 'Uploader',

    // Chatbot
    aiAssistant: 'AI Invoice Assistant',
    chatPlaceholder: 'Ask about your invoices...',
    suggestionTitle: 'Suggestions:',
    suggestionTotalSpend: 'What is my total spend?',
    suggestionTopVendor: 'Who is my top vendor?',
    suggestionMostPurchased: 'What is my most purchased item?',
    suggestionUnpaid: 'How much do I owe?',
    chatWelcome: 'Hello! I can analyze your invoice data. Ask me anything!',
    thinking: 'Thinking...',
    send: 'Send',

    // Smart Analysis
    smartAnalysisTitle: 'Smart Analysis Hub',
    aiSummary: 'AI-Powered Summary',
    showSummary: 'Generate AI Summary',
    hideSummary: 'Hide Summary',
    anomalyDetection: 'Anomaly Detection',
    showAnomalies: 'Detect Anomalies',
    hideAnomalies: 'Hide Anomalies',
    kpiGenerator: 'AI KPI Generator',
    kpiPlaceholder: 'Request a specific metric (e.g., "Total unpaid invoices")',
    generate: 'Generate',
    suggestMore: 'Suggest Indicators',
    dataVisualization: 'Data Visualization',
    hideChart: 'Hide Chart',
    chartXAxis: 'Dimension (X-Axis)',
    chartYAxis: 'Metric (Y-Axis)',
    axisVendor: 'Vendor',
    axisDate: 'Date',
    axisStatus: 'Status',
    axisTotal: 'Total Amount',
    noAnomaliesFound: 'Great! No anomalies or irregularities found in your invoices.',
    generateKpiPrompt: 'Generate',
  },
  ar: {
    // General
    appName: 'مستخرج الفواتير الذكي',
    toggleLanguage: 'English',
    loading: 'جار التحميل...',
    usd: 'دولار',
    jod: 'د.أ',
    close: 'إغلاق',
    cancel: 'إلغاء',
    delete: 'حذف',
    actions: 'إجراءات',
    exportToExcel: 'تصدير إلى Excel',
    columns: 'الأعمدة',
    toggleColumns: 'إظهار/إخفاء الأعمدة',
    show: 'إظهار',
    invoiceFile: 'ملف الفاتورة',

    // Auth
    login: 'دخول',
    loginTitle: 'تسجيل الدخول',
    loginSubtitle: 'مرحباً بك، يرجى تسجيل الدخول للمتابعة',
    loggingIn: 'جارِ تسجيل الدخول...',
    signup: 'أنشئ حساباً',
    signupTitle: 'إنشاء حساب جديد',
    signupSubtitle: 'انضم إلينا! الأمر لا يستغرق سوى دقيقة.',
    signingUp: 'جارِ إنشاء الحساب...',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    passwordPlaceholder: 'أدخل كلمة المرور',
    welcome: 'مرحباً',
    loginPrompt: 'ليس لديك حساب؟',
    signupPrompt: 'هل لديك حساب بالفعل؟',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    userExists: 'البريد الإلكتروني مسجل بالفعل.',
    signupSuccess: 'تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.',
    signupError: 'حدث خطأ أثناء إنشاء الحساب. يرجى المحاولة مرة أخرى.',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',

    // Dashboard
    dashboardTitle: 'لوحة تحكم الفواتير',
    noFileSelected: 'لم يتم اختيار ملف',
    fileSelected: 'الملف المختار:',
    processInvoice: 'معالجة الفاتورة',
    processing: 'جاري تحليل الفاتورة...',
    analyzingLayout: 'جاري تحليل تخطيط المستند...',
    extractingText: 'استخراج النصوص والأرقام...',
    identifyingLineItems: 'التعرف على بنود الفاتورة...',
    verifyingTotals: 'التحقق من المجاميع والمبالغ...',
    almostDone: 'شارفنا على الانتهاء، يتم تجهيز النتائج...',
    extractionError: 'حدث خطأ أثناء استخراج البيانات. يرجى تجربة ملف آخر.',
    extractionErrors: 'تعذر معالجة {count} ملف.',
    noInvoices: 'لا توجد فواتير مشتريات حتى الآن. قم برفع فاتورة للبدء.',
    newlyExtractedInvoices: 'الفواتير المستخرجة حديثاً',
    savedInvoices: 'فواتير المشتريات',
    saveInvoice: 'حفظ الفاتورة',
    saveAllInvoices: 'حفظ الكل',
    clearAll: 'مسح الكل',
    saving: 'جارِ الحفظ...',
    invoiceSaved: 'تم حفظ بيانات الفاتورة بنجاح!',
    saveError: 'فشل حفظ الفاتورة: ',
    saveAllError: 'تعذر حفظ بعض الفواتير. يرجى المراجعة والمحاولة مرة أخرى.',
    reason: 'السبب',
    addNewInvoice: 'إضافة فاتورة مشتريات جديدة',
    addManually: 'إضافة يدوية',
    manualInvoiceEntry: 'إدخال فاتورة يدوية',
    backToInvoices: 'العودة للفواتير',
    uploadAndProcessInvoice: 'رفع ومعالجة فاتورة',
    invoiceDetails: 'تفاصيل فاتورة المشتريات',
    deleteInvoice: 'حذف فاتورة المشتريات',
    deleteConfirmTitle: 'تأكيد الحذف',
    deleteConfirmMessage: 'هل أنت متأكد من رغبتك في حذف فاتورة المشتريات هذه؟ لا يمكن التراجع عن هذا الإجراء.',
    deleteSelected: 'حذف المحدد',
    deleteSelectedConfirmMessage: 'هل أنت متأكد من حذف الفواتير المحددة وعددها {count}؟ لا يمكن التراجع عن هذا الإجراء.',
    countSelected: '{count} محدد',
    invoiceDeleted: 'تم حذف فاتورة المشتريات بنجاح.',
    invoicesDeleted: 'تم حذف الفواتير المحددة بنجاح.',
    grandTotal: 'المجموع الكلي',
    totalInvoices: 'مجموع الفواتير',
    uploadBoxTitle: 'إضافة فاتورة مشتريات جديدة',
    uploadBoxSubtitle: 'يدعم PDF، الصور، Excel، و Word.',
    chooseFile: 'اختر ملفات',
    uploadDocument: 'رفع مستند',
    docSubtitle: 'PDF, Word, Excel',
    uploadImage: 'رفع صورة',
    imgSubtitle: 'JPG, PNG',
    uploadPDF: 'رفع ملف',
    scanWithCamera: 'مسح بالكاميرا',
    fromScanner: 'من الماسح الضوئي',
    cancelUpload: 'إلغاء الرفع',
    searchPlaceholder: 'ابحث بالرقم، البائع، العميل...',
    filterItem: 'بحث باسم الصنف',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    clearFilters: 'مسح الفلاتر',
    minAmount: 'أقل مبلغ',
    maxAmount: 'أعلى مبلغ',
    listView: 'عرض القائمة',
    gridView: 'عرض الشبكة',
    processingCost: 'تكلفة المعالجة',
    totalUnpaidAmount: 'قيمة غير المدفوع',
    topVendorStat: 'أكثر مورد',
    topItemStat: 'أكثر صنف',

    // Camera
    capture: 'التقاط',
    retake: 'إعادة الالتقاط',
    usePhoto: 'استخدام الصورة',
    noCameraAccess: 'لا يمكن الوصول إلى الكاميرا. يرجى التحقق من الأذونات.',
    or: 'أو',
    uploadImageOrPDF: 'رفع ملف (PDF/Word/Excel/Img)',

    // Payment Status
    paidInvoices: 'الفواتير المدفوعة',
    unpaidInvoices: 'الفواتير غير المدفوعة',
    markAsPaid: 'تحديد كمدفوع',
    invoiceStatusUpdated: 'تم تحديث حالة الفاتورة بنجاح.',
    paid: 'مدفوعة',
    unpaid: 'غير مدفوعة',
    paymentStatus: 'حالة الدفع',
    filterByStatus: 'تصفية حسب الحالة',
    all: 'الكل',


    // Invoice Table Headers
    invoiceNumber: 'رقم الفاتورة',
    vendorName: 'البائع',
    customerName: 'العميل',
    invoiceDate: 'التاريخ',
    totalAmount: 'المبلغ الإجمالي',
    items: 'البنود',
    description: 'الوصف',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    total: 'الإجمالي',
    addItem: 'إضافة بند',
    removeItem: 'حذف',
    uploader: 'المستخدم',
    
    // Chatbot
    aiAssistant: 'مساعد الفواتير الذكي',
    chatPlaceholder: 'اسأل عن فواتيرك...',
    suggestionTitle: 'اقتراحات:',
    suggestionTotalSpend: 'كم مجموع صرفياتي؟',
    suggestionTopVendor: 'من هو المورد الأكثر تعاملاً؟',
    suggestionMostPurchased: 'ما هو الصنف الأكثر شراء؟',
    suggestionUnpaid: 'كم علي ديون؟',
    chatWelcome: 'مرحباً! يمكنني تحليل بيانات فواتيرك. اسألني أي شيء!',
    thinking: 'يفكر...',
    send: 'إرسال',

    // Smart Analysis
    smartAnalysisTitle: 'التحليل الذكي المتكامل',
    aiSummary: 'ملخص مدعوم بالذكاء الاصطناعي',
    showSummary: 'إظهار الملخص الذكي',
    hideSummary: 'إخفاء الملخص',
    anomalyDetection: 'كشف الحالات الغريبة',
    showAnomalies: 'إظهار كاشف الحالات الغريبة',
    hideAnomalies: 'إخفاء الكاشف',
    kpiGenerator: 'مولد مؤشرات الأداء بالذكاء الاصطناعي',
    kpiPlaceholder: 'اطلب مؤشر أداء مخصص (مثال: "إجمالي الفواتير غير المدفوعة")',
    generate: 'إنشاء',
    suggestMore: 'اقترح المزيد من المؤشرات',
    dataVisualization: 'تصور البيانات',
    hideChart: 'إخفاء التصور البياني',
    chartXAxis: 'البعد (المحور السيني)',
    chartYAxis: 'المقياس (المحور الصادي)',
    axisVendor: 'البائع',
    axisDate: 'التاريخ',
    axisStatus: 'حالة الدفع',
    axisTotal: 'المجموع (JOD)',
    noAnomaliesFound: 'ممتاز! لا توجد حالات غريبة أو غير طبيعية في الفواتير.',
    generateKpiPrompt: 'إنشاء',
  }
};
